version: '3.3'
services:
  dev:
    container_name: payment-service
    image: payment-service:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    environment: 
      MONGO_URI: mongodb://mongodb:27017/payment-service-dev
      PORT: 3000
    ports:
      - 3000:3000
    networks:
      - payment-service-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - payment-service-network
    restart: always
  prod:
    container_name: payment-service-prod
    image: payment-service-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    environment: 
      MONGO_URI: mongodb://mongodb:27017/payment-service-prod
      PORT: 3000
    ports:
      - 3000:3000
    networks:
      - payment-service-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
    payment-service-network:
      driver: bridge